### ISSUE TITLE
about the "undici" error

### ISSUE THREAD

**Issue by leo-je** [transitive-bullshit/chatgpt-api#105]
hello,when I send a message about "Write a singleton pattern in Java.",it throw a "undici" error:
-------------------
/app/qqbot/service/bin/node_modules/undici/lib/fetch/index.js:1921
        fetchParams.controller.controller.error(new TypeError('terminated', {
                                                ^

TypeError: terminated
    at Fetch.onAborted (/app/qqbot/service/bin/node_modules/undici/lib/fetch/index.js:1921:49)
    at Fetch.emit (node:events:390:28)
    at Fetch.emit (node:domain:475:12)
    at Fetch.terminate (/app/qqbot/service/bin/node_modules/undici/lib/fetch/index.js:93:10)
    at Object.onError (/app/qqbot/service/bin/node_modules/undici/lib/fetch/index.js:2062:34)
    at Request.onError (/app/qqbot/service/bin/node_modules/undici/lib/core/request.js:265:27)
    at null.errorRequest (/app/qqbot/service/bin/node_modules/undici/lib/client.js:1739:13)
    at TLSSocket.onSocketClose (/app/qqbot/service/bin/node_modules/undici/lib/client.js:998:5)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)

----------------
how can i do for that?

**Comment by transitive-bullshit** [comment]
@leo-je as a temporary constraint, this package requires node >= 18 because of this `undici` issue. See the note at the top of the readme for details.

**Comment by leo-je** [comment]
> 

my nodejs version is 19.2

**Comment by leo-je** [comment]
> @leo-je as a temporary constraint, this package requires node >= 18 because of this `undici` issue. See the note at the top of the readme for details.
But sometimes it is successful.It may be my network problem.
-----------
TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:14178:53)
    at Fetch.emit (node:events:513:28)
    at Fetch.emit (node:domain:489:12)
    at Fetch.terminate (node:internal/deps/undici/undici:13438:14)
    at Object.onError (node:internal/deps/undici/undici:14273:36)
    at Request.onError (node:internal/deps/undici/undici:7758:31)
    at errorRequest (node:internal/deps/undici/undici:9917:17)
    at TLSSocket.onSocketClose (node:internal/deps/undici/undici:9368:9)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12) {
  [cause]: SocketError: other side closed
      at TLSSocket.onSocketEnd (node:internal/deps/undici/undici:9347:26)
      at TLSSocket.emit (node:events:525:35)
      at TLSSocket.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at pr.....
    }
  }
}

**Comment by kongleeme** [comment]
I still have this problem. Node version 18.4 
<img width="628" alt="WechatIMG519" src="https://user-images.githubusercontent.com/12163733/219295106-3e6c7455-dab7-451b-9843-aaee112821d4.png">
