### ISSUE TITLE
Something wrong with google login

### ISSUE THREAD

**Issue by bhhbazinga** [transitive-bullshit/chatgpt-api#178]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

I deployed the application on linux and opened the browser on my windows through X11 SERVER

### Describe the Bug

Error: No element found for selector: button[data-provider="google"]
    at assert (/home/bhh/chatgpt-api/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at IsolatedWorld.click (/home/bhh/chatgpt-api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:221:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getOpenAIAuth (/home/bhh/chatgpt-api/src/openai-auth.ts:141:9)
    at ChatGPTAPIBrowser.initSession (/home/bhh/chatgpt-api/src/chatgpt-api-browser.ts:136:7)
    at main (/home/bhh/chatgpt-api/demos/demo-conversation-browser.ts:26:3)

**Comment by AprilNEA** [comment]
The same error.

**Comment by transitive-bullshit** [comment]
https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.3.5 should fix this.

Huge thanks to @suhaotian for the PR https://github.com/transitive-bullshit/chatgpt-api/pull/205

Please re-open if you're still running into this after upgrading.
