### ISSUE TITLE
Support for node v16

### ISSUE THREAD

**Issue by mvtavares** [transitive-bullshit/chatgpt-api#297]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

NodeJS v16.19.0
MacOS 12.6

### Describe the Bug

Hello @transitive-bullshit , nice library !

I was trying to use the lib with node 16 because i want to use it as a github action, but i couldn't make it work even installing a polyfill like described in the docs. I'm always getting the below error:

`/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/node_modules/chatgpt/build/index.js:15
  throw new Error("Invalid environment: global fetch not defined");

^
Error: Invalid environment: global fetch not defined
    at Module.3564 (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/node_modules/chatgpt/build/index.js:15:1)
    at __nccwpck_require__ (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1)
    at Object.86[9](https://github.com/mvtavares/chatgpt-ts-action/actions/runs/4087514132/jobs/7048119161#step:3:10)7 (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/lib/chatgpt-api.js:36:1)
    at __nccwpck_require__ (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1)
    at Object.3[10](https://github.com/mvtavares/chatgpt-ts-action/actions/runs/4087514132/jobs/7048119161#step:3:11)9 (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/lib/main.js:36:1)
    at __nccwpck_require__ (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1)
    at /home/runner/work/chatgpt-ts-action/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/chatgpt-ts-action/chatgpt-ts-action/dist/index.js:27232:12)
    at Module._compile (node:internal/modules/cjs/loader:[11](https://github.com/mvtavares/chatgpt-ts-action/actions/runs/4087514132/jobs/7048119161#step:3:12)05:[14](https://github.com/mvtavares/chatgpt-ts-action/actions/runs/4087514132/jobs/7048119161#step:3:15))
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/mvtavares/chatgpt-ts-action/actions/runs/4087514132/jobs/7048119161#step:3:16)9:10)`

Do you know how can i fix this?

**Comment by transitive-bullshit** [comment]
The error you're getting is saying that the `fetch` polyfill isn't installed.

Can you paste your full code for how you're polyfillng and then importing this lib?

**Comment by mvtavares** [comment]
Yes, sure. The code is here:

[Test PR](https://github.com/mvtavares/chatgpt-ts-action/tree/test_pr)

With the import to unfetch/polyfil [here](https://github.com/mvtavares/chatgpt-ts-action/blob/test_pr/src/main.ts), i get another error:

`ReferenceError: self is not defined
    at Object.8543 (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/node_modules/unfetch/polyfill/index.js:1:1)
    at __nccwpck_require__ (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1)
    at Object.3109 (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/lib/main.js:36:1)
    at __nccwpck_require__ (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1)
    at /Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/startup:4:1`

**Comment by mvtavares** [comment]
Oh, i got it working installing this: https://www.npmjs.com/package/isomorphic-fetch

I can open a PR to add this to the docs, wdyt?

**Comment by transitive-bullshit** [comment]
@mvtavares sounds good :) please just add a link to the polyfill section of their readme to the places where our readme currently links to a `guide`. Thanks! 🙏

**Comment by acgtap** [comment]
> Yes, sure. The code is here:
> 
> [Test PR](https://github.com/mvtavares/chatgpt-ts-action/tree/test_pr)
> 
> With the import to unfetch/polyfil [here](https://github.com/mvtavares/chatgpt-ts-action/blob/test_pr/src/main.ts), i get another error:
> 
> `ReferenceError: self is not defined at Object.8543 (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/node_modules/unfetch/polyfill/index.js:1:1) at __nccwpck_require__ (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1) at Object.3109 (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/lib/main.js:36:1) at __nccwpck_require__ (/Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/bootstrap:21:1) at /Users/marvin/dev/projects/mvtavares/chatgpt-ts-action/webpack:/chatgpt-ts-action/webpack/startup:4:1`

Me too. Is there any solution？

**Comment by mvtavares** [comment]
Try this one @acgtap: https://www.npmjs.com/package/isomorphic-fetch

It worked for me.
