### ISSUE TITLE
SyntaxError: Invalid regular expression Encoder.js

### ISSUE THREAD

**Issue by vladimir1408v** [transitive-bullshit/chatgpt-api#342]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v16.18.0, Linux version 4.9-ndm-5

### Describe the Bug

When you run the script, an error appears, tell me what the problem may be

```
SyntaxError: Invalid regular expression: /'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+/: Invalid property name
    at Object.<anonymous> (/opt/root/node_modules/gpt-3-encoder/Encoder.js:68:13)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/root/node_modules/gpt-3-encoder/index.js:1:28)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
~ #
```

**Comment by transitive-bullshit** [comment]
This is a bug with https://github.com/latitudegames/GPT-3-Encoder

Definitely looking to remove this dependency.

For now, maybe try upgrading your node.js version to v18 or v19.

**Comment by transitive-bullshit** [comment]
Try the new version https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.6.0

It replaces the troublesome gpt-3-encoder with a better dependency.
