### ISSUE TITLE
Error: The text contains a special token that is not allowed: <|endoftext|>

### ISSUE THREAD

**Issue by ulzhang** [transitive-bullshit/chatgpt-api#404]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node: v18.14.2

### Describe the Bug

I am running the demo commands and get an error.

```
➜  chatgpt-api git:(main) npx tsx demos/demo-on-progress.ts
Write a python version of bubble sort. Do not include example usage.
Error: The text contains a special token that is not allowed: <|endoftext|>
    at module.exports.__wbindgen_error_new (/Users/kevinzhang/git/nodegpt/chatgpt-api/node_modules/@dqbd/tiktoken/dist/node/_tiktoken.js:414:17)
    at wasm://wasm/00fdfe62:wasm-function[29]:0x2b7f4
    at wasm://wasm/00fdfe62:wasm-function[171]:0x5403e
    at Tiktoken.encode (/Users/kevinzhang/git/nodegpt/chatgpt-api/node_modules/@dqbd/tiktoken/dist/node/_tiktoken.js:268:18)
    at Module.encode (/Users/kevinzhang/git/nodegpt/chatgpt-api/src/tokenizer.ts:7:20)
    at ChatGPTAPI._getTokenCount (/Users/kevinzhang/git/nodegpt/chatgpt-api/src/chatgpt-api.ts:441:22)
    at ChatGPTAPI._buildPrompt (/Users/kevinzhang/git/nodegpt/chatgpt-api/src/chatgpt-api.ts:389:40)
    at ChatGPTAPI.sendMessage (/Users/kevinzhang/git/nodegpt/chatgpt-api/src/chatgpt-api.ts:215:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/Users/kevinzhang/git/nodegpt/chatgpt-api/demos/demo-on-progress.ts:21:15)
```

**Comment by Chanzhaoyu** [comment]
`The text contains a special token that is not allowed: <|endoftext|>`

Also after the upgrade

**Comment by transitive-bullshit** [comment]
@ulzhang @Chanzhaoyu this should now be fixed in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.8.3

Sorry about that && thanks for the report.
