### ISSUE TITLE
always meet error from @dqbd/tiktoken and cause memory leak

### ISSUE THREAD

**Issue by yunyu950908** [transitive-bullshit/chatgpt-api#495]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

```
node/18.14.0
Darwin 192.168.1.6 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64
```

### Describe the Bug

try to run this piece of code. it always encounter an error

```js
import { encoding_for_model } from "@dqbd/tiktoken";

function main() {
  let n = 100000;
  const input = "Hello, world!";
  try {
    while (n > 0) {
      const res = encoding_for_model("gpt-3.5-turbo").encode(input);
      n--;
      // console.log(n, res);
      console.log(n);
    }
  } catch (error) {
    console.log(error);
  }
}

main();
```

an error occurred
```
TypeError: The encoded data was not valid for encoding utf-8
    at TextDecoder.decode (node:internal/encoding:433:16)
    at getStringFromWasm0 (/Users/todd/src/playground/tmp/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:111:30)
    at module.exports.__wbindgen_error_new (/Users/todd/src/playground/tmp/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:398:27)
    at wasm://wasm/00b63e2e:wasm-function[59]:0x2942d
    at module.exports.encoding_for_model (/Users/todd/src/playground/tmp/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:175:14)
    at main (file:///Users/todd/src/playground/tmp/tokenizer.js:8:19)
    at file:///Users/todd/src/playground/tmp/tokenizer.js:30:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_ENCODING_INVALID_ENCODED_DATA'
}
```

and when I integrated it in our product running in production environment, it always meet memory leak and cause OOM kill.

---

And then I replace the tokenizer solution to this, problem fixed
```ts
import GPT3Tokenizer from 'gpt3-tokenizer'

const tokenizer = new GPT3Tokenizer({ type: 'gpt3' })

function countTokens(str: string) {
  const encoded = tokenizer.encode(str)
  return encoded.bpe.length
}

// https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
export function countMessagesTokens(messages: ChatMessage[]) {
  let n = 0
  for (const m of messages) {
    n += countTokens(m.content)
    n += countTokens(m.role)
  }
  return n + 2
}
```

ref: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by yunyu950908** [comment]
https://github.com/transitive-bullshit/chatgpt-api/blob/9932fca55c415ce60951354f64e08b2fef0fc4df/package.json#L40

**Comment by transitive-bullshit** [comment]
cc @dqbd I think this may belong as an issue in https://github.com/dqbd/tiktoken?

**Comment by dqbd** [comment]
The core issue here is that the encoder is being created in a loop. To prevent memory leaks, you ought to free the instance after the usage has been completed.

```
import { encoding_for_model } from "@dqbd/tiktoken";

function main() {
  let n = 100000;
  const input = "Hello, world!";
  const encoder = encoding_for_model("gpt-3.5-turbo");
  try {
    while (n > 0) {
      const res = encoder.encode(input);
      n--;
      // console.log(n, res);
      console.log(n);
    }
  } catch (error) {
    console.log(error);
  } finally {
    encoder.free();
  }
}

main();
```

**Comment by transitive-bullshit** [comment]
thanks for the great answer @dqbd 🙏
