### ISSUE TITLE
ChatGPTUnofficialProxyAPI Does not work

### ISSUE THREAD

**Issue by ashuvax** [transitive-bullshit/chatgpt-api#516]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

all

### Describe the Bug

FetchError: request to https://bypass.duti.tech/api/conversation failed, reason: Hostname/IP does not match certificate's altnames: Host: bypass.duti.tech. is not in the cert's altnames: DNS:

**Comment by sam-hieken** [comment]
Similar (or same) issue here.

```
TypeError: Failed to parse URL from
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at async fetchSSE (/node_modules/chatgpt/build/index.js:46:15) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:230:25)
      at fetchSSE (/node_modules/chatgpt/build/index.js:46:21)
      at /node_modules/chatgpt/build/index.js:556:7
      at new Promise (<anonymous>) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
```

**Comment by transitive-bullshit** [comment]
NOTE: I strongly recommend using the official API via `ChatGPTAPI` going forwards. The unofficial API proxies are not robust and will continue to have intermittent downtimes.
