### ISSUE TITLE
how to solve "TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded" ?

### ISSUE THREAD

**Issue by shumintao** [transitive-bullshit/chatgpt-api#528]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

```
   "dependencies": {
        "ajv": "8.12.0",
        "chatgpt": "3.5.1",
        "consul": "1.2.0",
        "puppeteer": "19.7.3",
        "uuid": "^9.0.0"
      }
```

### Describe the Bug

```
TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
    at Timeout.<anonymous> (/chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:63:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Retry login in 60s.
TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
Retry login in 60s.
    at Timeout.<anonymous> (/chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:63:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Retry login in 60s.
TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
    at Timeout.<anonymous> (/chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:63:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
    at Timeout.<anonymous> (/chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:63:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by transitive-bullshit** [comment]
the browser version (v3 branch) is no longer supported or maintained. sorry
