### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by cuongdnv2307** [transitive-bullshit/chatgpt-api#592]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node version : v18.16.1
Windows 11 

### Describe the Bug

I got the below error

Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
    at ChatGPTAPI.fetchCallImpl (main.js?attr=NWlR-sncM9PvO9IsjgmYJYLNIizg-ac57kqKv5nTKmfgLQ2njijxl0idxUoSQhvA:2923:25)
    at window.fetch [as _fetch] (main.js?attr=NWlR-sncM9PvO9IsjgmYJYLNIizg-ac57kqKv5nTKmfgLQ2njijxl0idxUoSQhvA:2925:55)
    at Promise.then.promptTokens (chatgpt-api.ts:251:1)
    at new Promise (<anonymous>)
    at ChatGPTAPI.sendMessage (chatgpt-api.ts:182:1)
    at async example (App.js:12:1)

**Comment by kumavis** [comment]
same issue, chatgpt@5.2.5 on chrome

**Comment by kumavis** [comment]
workaround:
```js
    const api = new ChatGPTAPI({ apiKey })
    // workaround for https://github.com/transitive-bullshit/chatgpt-api/issues/592
    api._fetch = self.fetch.bind(self)
    ```

**Comment by Martin-Gregory-LG** [comment]
In case it helps someone else, it was solved for me by using regular function rather than arrow function

``` javascript
const useGpt = async () => {
  const api = new ChatGPTAPI({
    apiKey,
  });
};

async function useGpt() {
  const api = new ChatGPTAPI({
    apiKey,
  });
}
```

**Comment by Insanity19** [comment]
solution for macOS
```js
const api = new ChatGPTAPI({
      apiKey,
      fetch: window.fetch.bind(window),
  })
```

**Comment by yaochiqkl** [comment]
same issue on Chrome version 122.0.6261.112 macOS (arm64)
<img width="1238" alt="image" src="https://github.com/transitive-bullshit/chatgpt-api/assets/13565033/1dba024a-e7f8-4b92-9e4b-d60ea0b40685">

**Comment by zangguojun** [comment]
> workaround:
> 
> ```js
>     const api = new ChatGPTAPI({
>       apiKey,
>       // workaround for https://github.com/transitive-bullshit/chatgpt-api/issues/592
>       fetch: self.fetch.bind(self),
>     })
> ```

 I did solve the fetch problem in the above way, but there were new problems.
```
   <div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:386" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">chatgpt.js?v=4d2c40ad:386</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">ReferenceError: Buffer is not defined
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.stringify [as serialize] (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:386:16" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">chatgpt.js?v=4d2c40ad:386:16</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:589:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">chatgpt.js?v=4d2c40ad:589:28</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async ChatGPTAPI._defaultUpsertMessage (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:2158:5" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">chatgpt.js?v=4d2c40ad:2158:5</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async Promise.all (<span class="devtools-link" title="http://localhost:5173/index 0" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">:5173/index 0</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container" style="display: inline-block; width: 533px; --monospace-font-size: 11px; --monospace-font-family: menlo,monospace; --source-code-font-size: 11px; --source-code-font-family: menlo,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | await in （匿名）（异步） |  
-- | -- | --


harset='utf-8'><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:386" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">chatgpt.js?v=4d2c40ad:386</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">ReferenceError: Buffer is not defined
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.stringify [as serialize] (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:386:16" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">chatgpt.js?v=4d2c40ad:386:16</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:589:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">chatgpt.js?v=4d2c40ad:589:28</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async ChatGPTAPI._defaultUpsertMessage (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="http://localhost:5173/node_modules/.vite/deps/chatgpt.js?v=4d2c40ad:2158:5" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">chatgpt.js?v=4d2c40ad:2158:5</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async Promise.all (<span class="devtools-link" title="http://localhost:5173/index 0" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">:5173/index 0</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container" style="display: inline-block; width: 533px; --monospace-font-size: 11px; --monospace-font-family: menlo,monospace; --source-code-font-size: 11px; --source-code-font-family: menlo,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;"><table class="stack-preview-container" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: block; width: 533px;"><tr style="box-sizing: border-box; min-width: 0px; min-height: 0px; height: 16px; line-height: 16px;"><td style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding-inline: 2px; color: rgb(31, 31, 31); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><td class="stack-preview-async-description" style="box-sizing: border-box; min-width: 0px; min-height: 0px; padding: 3px 0px 1px; font-style: italic; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding-inline: 2px; color: rgb(31, 31, 31); font-family: menlo, monospace; font-size: 11px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">await in （匿名）（异步）</td><td style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding-inline: 2px; color: rgb(31, 31, 31); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">
```

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package.
